package com.oskarro.queue.model

enum class Stage(name: String) {
    WYDANIE("WYDANIE"),
    NAWAZENIE("NAWAZENIE"),
    MIESZANIE("MIESZANIE"),
    MIESZANIE_ROZLEW("MIESZANIE I ROZLEW"),
    ROZSYPYWANIE("ROZSYPYWANIE"),
    SLEEVE("SLEEVE"),
    ZGRZEWANIE_DATOWANIE_ETYKIETOWANIE("ZGRZEWANIE, DATOWANIE, ETYKIETOWANIE"),
    PLOMBOWANIE("PLOMBOWANIE"),
    MAGAZYN("MAGAZYN"),
    KONIEC("KONIEC"),
    ERROR("ERROR");
}
