package com.oskarro.queue.model

enum class Stage(name: String, order: Int, var color: String = "#000000") {
    WYDANIE("WYDANIE", 0, "#E4E7FFCC"),
    NAWAZENIE("NAWAZENIE", 1, "#E4DBFFB2"),
    MIESZANIE("MIESZANIE", 2, "#E4C9FF8C"),
    MIESZANIE_ROZLEW("MIESZANIE I ROZLEW", 3, "#E4C1FF7A"),
    ROZSYPYWANIE("ROZSYPYWANIE", 4, "#E4B7FF65"),
    SLEEVE("SLEEVE", 5, "#E4ACFF4D"),
    ZGRZEWANIE_DATOWANIE_ETYKIETOWANIE("ZGRZEWANIE, DATOWANIE, ETYKIETOWANIE", 6, "#E49DFF2E"),
    PLOMBOWANIE("PLOMBOWANIE", 7, "#E497FF20"),
    MAGAZYN("MAGAZYN", 8, "#E488FF00"),
    KONIEC("KONIEC", 9, "#000000"),
    ERROR("ERROR", 10, "#E4FF9230");
}