package com.oskarro.queue.model

enum class Stage(name: String, order: Int) {
    WYDANIE("WYDANIE", 0),
    NAWAZENIE("NAWAZENIE", 1),
    MIESZANIE("MIESZANIE", 2),
    MIESZANIE_ROZLEW("MIESZANIE I ROZLEW", 3),
    ROZSYPYWANIE("ROZSYPYWANIE", 4),
    SLEEVE("SLEEVE", 5),
    ZGRZEWANIE_DATOWANIE_ETYKIETOWANIE("ZGRZEWANIE, DATOWANIE, ETYKIETOWANIE", 6),
    PLOMBOWANIE("PLOMBOWANIE", 7),
    MAGAZYN("MAGAZYN", 8),
    KONIEC("KONIEC", 9),
    ERROR("ERROR", 10);
}
